/* Generated By:JJTree&JavaCC: Do not edit this line. SQL_parserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SQL_parserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CREATE_TABLE = 6;
  /** RegularExpression Id. */
  int INSERT_INTO = 7;
  /** RegularExpression Id. */
  int VALUES = 8;
  /** RegularExpression Id. */
  int SELECT = 9;
  /** RegularExpression Id. */
  int FROM = 10;
  /** RegularExpression Id. */
  int WHERE = 11;
  /** RegularExpression Id. */
  int COUNT = 12;
  /** RegularExpression Id. */
  int SUM = 13;
  /** RegularExpression Id. */
  int PERIOD = 14;
  /** RegularExpression Id. */
  int AS = 15;
  /** RegularExpression Id. */
  int INT = 16;
  /** RegularExpression Id. */
  int VARCHAR = 17;
  /** RegularExpression Id. */
  int PRIMARY_KEY = 18;
  /** RegularExpression Id. */
  int SQL_String = 19;
  /** RegularExpression Id. */
  int SEMICOLON = 20;
  /** RegularExpression Id. */
  int COMMA = 21;
  /** RegularExpression Id. */
  int L_PAREN = 22;
  /** RegularExpression Id. */
  int R_PAREN = 23;
  /** RegularExpression Id. */
  int ASTERISK = 24;
  /** RegularExpression Id. */
  int LT = 25;
  /** RegularExpression Id. */
  int GT = 26;
  /** RegularExpression Id. */
  int EQ = 27;
  /** RegularExpression Id. */
  int NE = 28;
  /** RegularExpression Id. */
  int AND = 29;
  /** RegularExpression Id. */
  int OR = 30;
  /** RegularExpression Id. */
  int IDENTIFIER = 31;
  /** RegularExpression Id. */
  int LETTER = 32;
  /** RegularExpression Id. */
  int PART_LETTER = 33;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 34;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"create table\"",
    "\"insert into\"",
    "\"values\"",
    "\"select\"",
    "\"from\"",
    "\"where\"",
    "\"count\"",
    "\"sum\"",
    "\".\"",
    "\"as\"",
    "\"int\"",
    "\"varchar\"",
    "\"primary key\"",
    "<SQL_String>",
    "\";\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"*\"",
    "\"<\"",
    "\">\"",
    "\"=\"",
    "\"<>\"",
    "\"and\"",
    "\"or\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "<INTEGER_LITERAL>",
    "\"#\"",
  };

}
