/* Generated By:JavaCC: Do not edit this line. SQL_parserTreeConstants.java Version 5.0 */
package parser;

public interface SQL_parserTreeConstants
{
  public int JJTSQLSCRIPT = 0;
  public int JJTSQLOPERATOR = 1;
  public int JJTCREATE = 2;
  public int JJTATTRI_LIST = 3;
  public int JJTATTRI_LIST_UNIT = 4;
  public int JJTATTRI_INT = 5;
  public int JJTATTRI_VCHAR = 6;
  public int JJTQUERY = 7;
  public int JJTQUERYLIST = 8;
  public int JJTSELECTLIST = 9;
  public int JJTSELECTEXPRESSION = 10;
  public int JJTALIS_AST = 11;
  public int JJTFROMLIST = 12;
  public int JJTFROMLISTUNIT = 13;
  public int JJTWHERECLAUSE = 14;
  public int JJTSEARCHCOND = 15;
  public int JJTOPLEFTHANDSIDE = 16;
  public int JJTOPRIGHTHANDSIDE = 17;
  public int JJTALIS = 18;
  public int JJTALISL = 19;
  public int JJTALISR = 20;
  public int JJTCOUNT = 21;
  public int JJTSUM = 22;
  public int JJTINSERT = 23;
  public int JJTCOLUMN_IDENTIFIER_LIST = 24;
  public int JJTCOLUMN_IDENTIFIER = 25;
  public int JJTINSERT_VALUE_LIST = 26;
  public int JJTINSERT_VALUE = 27;
  public int JJTINSERT_VALUE_STRING = 28;


  public String[] jjtNodeName = {
    "SqlScript",
    "SqlOperator",
    "Create",
    "Attri_List",
    "Attri_List_Unit",
    "Attri_int",
    "Attri_vchar",
    "Query",
    "QueryList",
    "SelectList",
    "SelectExpression",
    "Alis_AST",
    "FromList",
    "FromListUnit",
    "WhereClause",
    "SearchCond",
    "OPLeftHandSide",
    "OPRightHandSide",
    "Alis",
    "AlisL",
    "AlisR",
    "Count",
    "Sum",
    "Insert",
    "Column_identifier_list",
    "Column_identifier",
    "insert_value_list",
    "insert_value",
    "insert_value_string",
  };
}
/* JavaCC - OriginalChecksum=38e5dea72e61af348033e81a057dfbdd (do not edit this line) */
